dest: web # 生成文件目录
site:
  url: / # 博客网址
  name: py-blog # 站点名称
  description: py-blog演示站点 # 站点描述
  keywords: python blog 博客 # 站点关键词
  icon: # 站点图标
lang: zh-CN # 站点语言
author: py-blog # 作者
theme: material # 博客主题
post_addr: origin # number|pinyin|origin (文章命名方式)

index: # 索引
  per_page: 10 # 每页文章数量
  preview: 150 # 文章预览(摘要)自动截取字数

rss: atom # atom|rss|False (atom规范/rss规范/不生成rss)
sitemap: True # 是否生成站点地图

seo_push: 
  baidu: http://data.zz.baidu.com/urls?site=https://blog.zcmimi.top&token=**************** #百度推送接口调用地址
  bing: https://ssl.bing.com/webmaster/api.svc/json/SubmitUrlbatch?apikey=******************************** #bing推送接口调用地址

repo: # 一键部署git仓库地址
  - git@e.coding.net:zcmimi/blog.git
  - git@github.com:zcmimi/zcmimi.github.io.git

server: # 动态服务器配置
  port: 3399 # 端口
  password: py-blog # 密码